### PR TITLE
fix: apiKey not set when calling geocoding.byId(...)

### LINKED ISSUE #26: Bug: `(new URL(...)).searchParams.get(...) is null` when calling maptilersdk.geocoding.byId(...)
Everything is in the title.
This is because when [calling `byId()` function](https://github.com/maptiler/maptiler-client-js/blob/5c887ee48d6f41b8c0032f3cb61734ab12e90ce2/src/services/geocoding.ts#L382C16-L382C16), the `apiKey` is not set in the URL that is passed to the `callFetch` function. But [the `callFetch` function](https://github.com/maptiler/maptiler-client-js/blob/5c887ee48d6f41b8c0032f3cb61734ab12e90ce2/src/callFetch.ts#L11) requires the api key to be set already.

### PR DESCRIPTION
**Pull request by toniopelo**
Fixes #26 
(See issue for the fix context)

### CODE REVIEW

**Comment by toniopelo** [comment]
@jonathanlurie Here is the PR for #26 :stuck_out_tongue:

**Comment by jonathanlurie** [comment]
Thanks a lot @toniopelo !

**Comment by toniopelo** [comment]
You're welcome :). When can we expect this patch to be released on npm @jonathanlurie ?

**Comment by jonathanlurie** [comment]
Hopefully this week! I first have to get this PR reviewed by a colleague https://github.com/maptiler/maptiler-client-js/pull/28 but it contains mostly basic maintenance so it should be pretty fast.

**Comment by toniopelo** [comment]
Nice, thanks for the quick reply!

**Comment by jonathanlurie** [comment]
Hey @toniopelo , the version v1.7.0 has just been published https://www.npmjs.com/package/@maptiler/client/v/1.7.0

**Pull request merged**
